import type { Metadata } from 'next'
import './globals.css'
import { Providers } from '@/app/providers'
import { ReactNode } from 'react'
import { GnbMenu } from '@/app/_component/gnb-menu'
import { PretendardFont } from '@/app/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang={'ko'} dir={'ltr'}>
      <body className={`antialiased ${PretendardFont.variable} font-sans min-w-[1400px]`}>
        <Providers themeProps={{ attribute: 'class', defaultTheme: 'dark' }}>
          <GnbMenu />
          <main className="relative flex-col overflow-x-hidden overflow-y-auto">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
